rosy: Update missing ADSP blobs
* E /vendor/bin/adsprpcd: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/apps_std_imp.c:729:Error 45: fopen failed for libdirac-capiv2.so. (No such file or directory)
* from daisy